{
 "title": "Istio Client Server Performance",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client_namespace",
    "label": "Client Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "client_pod",
    "label": "Client Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$client_namespace\"}, pod)"
    }
   },
   {
    "name": "client_pod_ip",
    "label": "Client Pod IP",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$client_namespace\", pod=~\"$client_pod\"},  pod_ip)"
    }
   },
   {
    "name": "server_namespace",
    "label": "Server Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "server_pod",
    "label": "Server Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$server_namespace\"}, pod)"
    }
   },
   {
    "name": "server_pod_ip",
    "label": "Server Pod IP",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$server_namespace\", pod=~\"$server_pod\"}, pod_ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Client IP Address",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>$client_pod_ip</h1></center>"
   }
  },
  {
   "title": "Server IP Address",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<center><h1>$server_pod_ip</h1></center>"
   }
  },
  { "title": "Memory Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Client MEM Request/Limit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"$client_namespace\",pod=\"$client_pod\",container!=\"POD\",container!=\"istio-init\"} / 1024 / 1024",
     "legendFormat": "Request {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$client_namespace\",pod=\"$client_pod\",container!=\"POD\",container!=\"istio-init\"} / 1024 / 1024",
     "legendFormat": "Limit {{container}}"
    }
   ]
  },
  {
   "title": "Server MEM Request/Limit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"$server_namespace\",pod=\"$server_pod\",container!=\"POD\",container!=\"istio-init\"} / 1024 / 1024",
     "legendFormat": "Request {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$server_namespace\",pod=\"$server_pod\",container!=\"POD\",container!=\"istio-init\"} / 1024 / 1024",
     "legendFormat": "Limit {{container}}"
    }
   ]
  },
  {
   "title": "Client Memory Usage",
   "type": "graph",
   "description": "Client memory usage per container",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$client_namespace\",image!=\"\",pod=\"$client_pod\",container!=\"POD\",container!=\"istio-init\"} / 1024 / 1024",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Server Memory Usage",
   "type": "graph",
   "description": "Server memory usage per container",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$server_namespace\",image!=\"\",pod=\"$server_pod\",container!=\"POD\",container!=\"istio-init\"} / 1024 / 1024",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "CPU Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Client CPU Request/Limit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"$client_namespace\",pod=\"$client_pod\",container!=\"POD\",container!=\"istio-init\"}",
     "legendFormat": "Request {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$client_namespace\",pod=\"$client_pod\",container!=\"POD\",container!=\"istio-init\"}",
     "legendFormat": "Limit {{container}}"
    }
   ]
  },
  {
   "title": "Server CPU Request/Limit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"$server_namespace\",pod=\"$server_pod\",container!=\"POD\",container!=\"istio-init\"}",
     "legendFormat": "Request {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$server_namespace\",pod=\"$server_pod\",container!=\"POD\",container!=\"istio-init\"}",
     "legendFormat": "Limit {{container}}"
    }
   ]
  },
  {
   "title": "Client CPU Usage",
   "type": "graph",
   "description": "Client CPU usage per container",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$client_namespace\",image!=\"\",container!=\"POD\",container!=\"istio-init\",pod=\"$client_pod\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Server CPU Usage",
   "type": "graph",
   "description": "Server CPU usage per container",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$server_namespace\",image!=\"\",container!=\"POD\",container!=\"istio-init\",pod=\"$server_pod\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Envoy Listener Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Client Envoy Listener Downstream Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_listener_downstream_cx_active{namespace=\"$client_namespace\",pod_name=\"$client_pod\",listener_address=\"0.0.0.0_8080\"}",
     "legendFormat": "{{listener_address}}"
    }
   ]
  },
  {
   "title": "Server Envoy Listener Downstream Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_listener_downstream_cx_active{namespace=\"$server_namespace\",pod_name=\"$server_pod\",listener_address=\"0.0.0.0_15006\"}",
     "legendFormat": "{{listener_address}}"
    }
   ]
  },
  {
   "title": "Client Envoy Listener Downstream Active Connections per Worker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"envoy_listener_worker_.*_downstream_cx_active\",namespace=\"$client_namespace\",pod_name=\"$client_pod\",listener_address=\"0.0.0.0_8080\"}",
     "legendFormat": "{{listener_address}} - {{__name__}}"
    }
   ]
  },
  {
   "title": "Server Envoy Listener Downstream Active Connection per Worker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"envoy_listener_worker_.*_downstream_cx_active\",namespace=\"$server_namespace\",pod_name=\"$server_pod\",listener_address=\"0.0.0.0_15006\"}",
     "legendFormat": "{{listener_address}} - {{__name__}}"
    }
   ]
  },
  {
   "title": "Client Envoy Listener Outbound Downstream Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_listener_http_outbound_0_0_0_0_8080_downstream_rq{namespace=\"$client_namespace\",pod_name=\"$client_pod\",listener_address=\"0.0.0.0_8080\"}[1m])",
     "legendFormat": "{{listener_address}} ({{response_code_class}})"
    }
   ]
  },
  {
   "title": "Server Envoy Listener Inbound Downstream Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\"envoy_listener_http_inbound_.*_8080_downstream_rq\",namespace=\"$server_namespace\",pod_name=\"$server_pod\",listener_address=\"0.0.0.0_15006\"}[1m])",
     "legendFormat": "{{listener_address}} ({{response_code_class}})"
    }
   ]
  },
  { "title": "Envoy Cluster Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Client Envoy Outbound Cluster Upstream Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{namespace=\"$client_namespace\",pod_name=\"$client_pod\",cluster_name=\"outbound|8080||fortio-server.fortio.svc.cluster.local\"}",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Server Envoy Inbound Cluster Upstream Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{namespace=\"$server_namespace\",pod_name=\"$server_pod\",cluster_name=\"inbound|8080|http|fortio-server.fortio.svc.cluster.local\"}",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Client Envoy Outbound Cluster Upstream Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_active{namespace=\"$client_namespace\",pod_name=\"$client_pod\",cluster_name=\"outbound|8080||fortio-server.fortio.svc.cluster.local\"}",
     "legendFormat": "Active - {{cluster_name}}"
    },
    {
     "expr": "envoy_cluster_upstream_rq_pending_active{pod_name=\"$client_pod\",namespace=\"$client_namespace\",cluster_name=\"outbound|8080||fortio-server.fortio.svc.cluster.local\"}",
     "legendFormat": "Pending - {{cluster_name}}"
    }
   ]
  },
  {
   "title": "Server Envoy Inbound Cluster Upstream Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_active{namespace=\"$server_namespace\",pod_name=\"$server_pod\",cluster_name=\"inbound|8080|http|fortio-server.fortio.svc.cluster.local\"}",
     "legendFormat": "Active - {{cluster_name}}"
    },
    {
     "expr": "envoy_cluster_upstream_rq_pending_active{pod_name=\"$server_pod\",namespace=\"$server_namespace\",cluster_name=\"inbound|8080|http|fortio-server.fortio.svc.cluster.local\"}",
     "legendFormat": "Pending - {{cluster_name}}"
    }
   ]
  }
 ]
}