{
 "title": "Envoy Proxy Dashboard",
 "description": "Envoy proxy monitoring Dashboard with cluster and host level templates. ",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(envoy_cluster_upstream_cx_total, namespace)"
   },
   {
    "name": "pod_name",
    "label": "Pod Name",
    "query": "label_values(envoy_cluster_upstream_cx_total{namespace=~\"$namespace\"}, pod_name)"
   },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": "label_values(envoy_cluster_upstream_cx_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\"}, cluster_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Live servers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_server_live{namespace=~\"$namespace\", pod_name=~\"$pod_name\"})"
    }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(envoy_server_uptime{namespace=~\"$namespace\", pod_name=~\"$pod_name\"})"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated{namespace=~\"$namespace\", pod_name=~\"$pod_name\"})"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size{namespace=~\"$namespace\", pod_name=~\"$pod_name\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Clusters",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy{namespace=~\"$namespace\", pod_name=~\"$pod_name\"})  - sum(envoy_cluster_membership_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\"}))"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total{pod_name=~\"$pod_name\"})-sum(envoy_cluster_membership_healthy{pod_name=~\"$pod_name\"})) == bool 0"
    }
   ]
  },
  {
   "title": "Total upstream connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}({{cluster_name}})"
    }
   ]
  },
  {
   "title": "Active upstream connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pod_name}}({{cluster_name}})"
    }
   ]
  },
  {
   "title": "Total upstream requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_rq_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pod_name}}({{cluster_name}})"
    }
   ]
  },
  {
   "title": "Active upstream requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_rq_active{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pod_name}}({{cluster_name}})"
    }
   ]
  },
  {
   "title": "Upstream Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pod_name}} ({{cluster_name}}) - in"
    },
    {
     "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pod_name}} ({{cluster_name}}) - out"
    }
   ]
  },
  {
   "title": "Downstream Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=~\"$cluster\",host=~\"$hosts\"}[1m])",
     "legendFormat": "{{zone}} ({{host}}) - in"
    },
    {
     "expr": "irate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=~\"$cluster\",host=~\"$hosts\"}[1m])",
     "legendFormat": "{{zone}} ({{host}}) - out"
    }
   ]
  },
  {
   "title": "Downstream members",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_healthy{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})/count(envoy_cluster_membership_healthy{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})",
     "legendFormat": "{{pod_name}} ({{cluster_name}}) -  - healthy"
    },
    {
     "expr": "sum(envoy_cluster_membership_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})/count(envoy_cluster_membership_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})",
     "legendFormat": "{{pod_name}}({{cluster_name}}) - total"
    }
   ]
  }
 ]
}