{
 "title": "Envoy Service Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(envoy_cluster_upstream_cx_total, namespace)"
   },
   {
    "name": "pod_name",
    "label": "Pod Name",
    "query": "label_values(envoy_cluster_upstream_cx_total{namespace=~\"$namespace\"}, pod_name)"
   },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": "label_values(envoy_cluster_upstream_cx_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\"}, cluster_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Egress CPS / RPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "egress CPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "egress RPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "pending req to"
    },
    {
     "expr": "sum(rate(envoy_cluster_lb_healthy_panic{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "lb healthy panic RPS"
    }
   ]
  },
  {
   "title": "Total Connections / Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_active{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_active{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Cluster Membership",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(envoy_cluster_membership_change{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "membership changes [1m]"
    },
    {
     "expr": "sum(envoy_cluster_membership_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})",
     "legendFormat": "total membershiip"
    },
    {
     "expr": "sum(envoy_cluster_outlier_detection_ejections_active{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})",
     "legendFormat": "outlier ejections active"
    },
    {
     "expr": "sum(envoy_cluster_membership_healthy{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})",
     "legendFormat": "healthy members (active HC and outlier)"
    },
    {
     "expr": "sum(envoy_cluster_health_check_healthy{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})",
     "legendFormat": "healthy members (active HC only)"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{response_code_class!=\"5xx\",namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "Success Rate %"
    }
   ]
  },
  {
   "title": "4xx and 5xx % response rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{response_code_class=\"4xx\", namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "Response 4xx %"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{response_code_class=\"5xx\", namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "Response 5xx %"
    }
   ]
  },
  {
   "title": "Upstream Request Errors Rate",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "connect timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "pending failure ejection"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "pending overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "request timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_per_try_timeout{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "per try request timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_rx_reset{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "request reset"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_destroy_local_with_active_rq{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "destroy initialized from originating service"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_destroy_remote_active_rq{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "destroy initialized from remote service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_maintenance_mode{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "request failed maintenance mode"
    }
   ]
  },
  {
   "title": "Upstream Request Retry Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "request retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "request retry success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "request retry overflow"
    }
   ]
  },
  {
   "title": "Upstream Flow Control Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_paused_reading_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "paused reading from destination service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_resumed_reading_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "resumed reading from destination service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_backed_up_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "paused reading from originating service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_drained_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "resumed reading from originating service"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m])) by (le))",
     "legendFormat": "50th %ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m])) by (le))",
     "legendFormat": "95th %ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"}[1m])) by (le))",
     "legendFormat": "99th %ile"
    }
   ]
  },
  {
   "title": "request retry overflow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_retry_overflow{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})",
     "legendFormat": "request retry overflows"
    }
   ]
  },
  {
   "title": "request pending overflow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_overflow{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})",
     "legendFormat": "request pending overflows"
    }
   ]
  },
  {
   "title": "connection pool overflow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_pool_overflow{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})",
     "legendFormat": "pool overflows"
    }
   ]
  },
  {
   "title": "connection overflow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_overflow{namespace=~\"$namespace\", pod_name=~\"$pod_name\", cluster_name=~\"$cluster_name\"})",
     "legendFormat": "connection overflow"
    }
   ]
  }
 ]
}