---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-config
data:
  test.js: |
    import http from 'k6/http';
    export let options = {
      duration: `${__ENV.K6_DURATION}`,
      vus: `${__ENV.K6_VIRTUAL_USERS}`,
    };
    function randomString(length) {
      const charset = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
      let res = '';
      while (length--) res += charset[Math.random() * charset.length | 0];
      return res;
    };
    export default function() {
      let response = http.request('GET', `${__ENV.K6_TARGET_URL}`, `${randomString(`${__ENV.K6_REQUEST_SIZE}`)}`);
    };

  run.sh: |
    #!/usr/bin/env sh

    echo "Running performance test the following K6 environment variables"
    env | sort -f | grep "K6_"

    echo "Waiting for ${K6_TARGET_URL} to be reachable"
    until wget -T 1 -q --spider ${K6_TARGET_URL} > /dev/null 2>&1
    do
        echo -n .
        sleep 1
    done
    echo -e "\n${K6_TARGET_URL} is now reachable"

    echo "Starting k6 load test"
    k6 run --quiet /home/k6/test.js

    echo "Finished k6 load test"
    sleep infinity

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k6
  labels:
    account: k6

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6
  labels:
    app: k6
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6
  template:
    metadata:
      labels:
        app: k6
        version: 1.0.0
      annotations:
        sidecar.istio.io/statsInclusionPrefixes: reporter=,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grpc,wasm,component,cluster.outbound,,cluster.inbound
    spec:
      serviceAccountName: k6
      containers:
        - name: k6
          image: loadimpact/k6:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: K6_DURATION
              value: "5m"
            - name: K6_REQUEST_SIZE
              value: "50"
            - name: K6_TARGET_URL
              value: "http://service1:9091/"
            - name: K6_VIRTUAL_USERS
              value: "5"
          volumeMounts:
            - name: k6-config
              mountPath: /home/k6
          command: ["/bin/sh"]
          args: ["-c", "/home/k6/run.sh"]
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: k6-config
          configMap:
            name: k6-config
            defaultMode: 0777
