apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: query
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.21.0
  name: aspen-mesh-jaeger-query-np
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: tcp-query
    nodePort: 30003
  selector:
    app.kubernetes.io/component: query
    app.kubernetes.io/name: jaeger
  sessionAffinity: None
  type: NodePort
