apiVersion: v1
kind: Service
metadata:
  labels:
    app: kiali
    app.kubernetes.io/instance: kiali-server
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: kiali
    version: v1.30.0
  name: kiali-np
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 20001
    protocol: TCP
    targetPort: 20001
    nodePort: 30004
  selector:
    app.kubernetes.io/instance: kiali-server
    app.kubernetes.io/name: kiali
  sessionAffinity: None
  type: NodePort