all:
  hosts:
    master:
      ansible_host: 10.1.1.5
      ip: 10.1.1.5
      access_ip: 10.1.1.5
    aspen1:
      ansible_host: 10.1.1.6
      ip: 10.1.1.6
      access_ip: 10.1.1.6
    aspen2:
      ansible_host: 10.1.1.7
      ip: 10.1.1.7
      access_ip: 10.1.1.7
    aspen3:
      ansible_host: 10.1.1.8
      ip: 10.1.1.8
      access_ip: 10.1.1.8
    aspen4:
      ansible_host: 10.1.1.9
      ip: 10.1.1.9
      access_ip: 10.1.1.9
    worker1:
      ansible_host: 10.1.1.10
      ip: 10.1.1.10
      access_ip: 10.1.1.10
    worker2:
      ansible_host: 10.1.1.11
      ip: 10.1.1.11
      access_ip: 10.1.1.11
    worker3:
      ansible_host: 10.1.1.12
      ip: 10.1.1.12
      access_ip: 10.1.1.12
    worker4:
      ansible_host: 10.1.1.13
      ip: 10.1.1.13
      access_ip: 10.1.1.13
    worker5:
      ansible_host: 10.1.1.14
      ip: 10.1.1.14
      access_ip: 10.1.1.14
  children:
    kube-master:
      hosts:
        master:
    kube-node:
      hosts:
        aspen1:
        aspen2:
        aspen3:
        aspen4:
        worker1:
        worker2:
        worker3:
        worker4:
        worker5:
    etcd:
      hosts:
        master:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
