---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-config
data:
  test.js: |
    import http from 'k6/http';
    export let options = {
      vus: 5,
      stages: [
        { duration: "5m", target: 5 },
      ],
    };
    function randomString(length) {
      const charset = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
      let res = '';
      while (length--) res += charset[Math.random() * charset.length | 0];
      return res;
    }
    export default function() {
      let response = http.get(`${__ENV.TARGET_URL}`, `${randomString(${__ENV.REQUEST_SIZE})}`);
    };

  run.sh: |
    #!/usr/bin/env sh

    echo "Running run.sh with the following ENV"
    env | sort -f

    echo "Waiting for ${TARGET_URL} to be reachable"
    until wget -T 1 -q --spider ${TARGET_URL} > /dev/null 2>&1
    do
        echo -n .
        sleep 1
    done
    echo -e "\n${TARGET_URL} is now reachable"

    echo "Starting k6 load test"
    k6 run --quiet /home/k6/test.js

    echo "Finished k6 load test"
    sleep infinity

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k6
  labels:
    account: k6

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6
  labels:
    app: k6
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6
  template:
    metadata:
      labels:
        app: k6
        version: 1.0.0
    spec:
      serviceAccountName: k6
      containers:
        - name: k6
          image: loadimpact/k6:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TARGET_URL
              value: "http://service1:9091/"
            - name: REQUEST_SIZE
              value: "50"
          volumeMounts:
            - name: k6-config
              mountPath: /home/k6
          command: ["/bin/sh"]
          args: ["-c", "/home/k6/run.sh"]
          resources:
            requests:
              cpu: 500m
              memory: 512Mi

      volumes:
        - name: k6-config
          configMap:
            name: k6-config
            defaultMode: 0777
